version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_ptsp

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8082:8080
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src/:var/www/html
    ports:
      - "9000:9000"
  
  composer:
    image: composer:latest
    container_name: composer
    command: ["composer", "install"]
    depends_on:
      - php
    volumes:
      - ./src/code:/app
    restart: always